### ISSUE TITLE
Sensor is not created

### ISSUE THREAD

**Issue by LucTs** [Cavekeeper/Energy-consumption-Logarex#1]
Hi @Cavekeeper,

first of all, many thanks for the script. I do have exactly the same setup (Logarex LK13BD Energymeter, Wiedmann IR and Home Assistant).

Just installed your script following the readme. I do receive data from Weidmann, tested via the Tetsprogramm which comes with the Sensor. From HA Host logs I also can see the device has been successfully connected to HA.

After I finished the setup in HA, I did a restart and also manually triggered the automation to run the script but no sensor (zahlerstand) was created.

At the moment I´m not sure if the script itself works. 
I created a new bearer token.
I also checked if something is written to the /temp folder, which is not the case.

How can I debug if everything is working as expected?

**Comment by Cavekeeper** [comment]
The problem occurs not to the script.
It seems the connection to your HA instance would not work.
Please try to check the curl:
curl -X POST -H "Authorization: Bearer <your_token>" -H "Content-Type: application/json" -d "1234567890" <HA_server_IP>/api/states/sensor.zahlerstand

**Comment by LucTs** [comment]
Hi,

 I used the Terminal & SSH Addon in HA to test:

`curl -X GET -H "Authorization: Bearer <token>" -H "Content-Type: application/json" http://192.168.178.23:8123/api/`
which provides valid outpot of: API running.

Then I tested:
`curl -X POST -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d '{"state": "9000", "attributes": {"device_class": "energy","unit_of_measurement": "KW/h","friendly_name": "Zählerstand"}}' http://192.168.178.23:8123/api/states/sensor.stromzaehlerstand`
which is the sensor you create via the script. I just replaced the calculated "$value" with "9000". The sensor stromzaehlerstand has been created incl. given attributes.

If I put the same into your script (with $value instead of 9000), the sensor is not being updated.

So I guess something within the script is not working as expected.

**Comment by LucTs** [comment]
When I use the IP address below error message is written to the logs:

Logger: aiohttp.server
Source: components/api/__init__.py:263
First occurred: 21:23:20 (1 occurrences)
Last logged: 21:23:20
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 263, in post
    new_state = data.get("state")
AttributeError: 'int' object has no attribute 'get'

**Comment by LucTs** [comment]
I get the following output for `ha hardware info`:

serial:
- /dev/ttyUSB0
- /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_D309V61T-if00-port0
- /dev/ttyAMA0

-> USB seems to be connected an recognized

When I send: `echo -e "\x2F\x3F\x21\x0D\x0A" >/dev/ttyUSB0` the output is: /LOG4LK13BD202015

When I send (directly after command above): `echo -e "\x06\x30\x30\x30\x0D\x0A" >/dev/ttyUSB0` the output is: 

000
C.1.0(06138606)
0.0.0(001LOG0006138606)
F.F(0000)
1.8.0(009198.548*kWh)
C.7.1(00000000)
C.7.2(00000000)
C.7.3(00000000)
0.2.1(ver.02, 150228, 671A)
C.2.1(1601150829)
C.2.9(1601150829)
!

So I think reading IR Head is working as well.

I noticed that there is no "ttyDump1.data" file located in /tmp directory.

**Comment by LucTs** [comment]
Got it working.

Had to change the value of sleep between #wake up and #send data request from 1 to 1.3.

Many thanks again for the script!
